In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\t480\Desktop\price predection project\data_of_medal.csv")
df_medal = df[df['total_medal'] != 0]
df_name_of_country = pd.read_csv(r'C:\Users\t480\Desktop\price predection project\countries.csv')
df = pd.concat([df_name_of_country, df_medal],axis=1)

In [5]:
df = df.drop(['name_of_country'], axis=1)

In [ ]:
df = df.drop(['Unnamed: 0'], axis = 1)

In [7]:
df

,countries,gold_medal,silver_medal,bronze_medal,total_medal,url_flag
0,United States,40,44,42,126,https://static.files.bbci.co.uk/core/website/a...
1,China,40,27,24,91,https://static.files.bbci.co.uk/core/website/a...
2,Japan,20,12,13,45,https://static.files.bbci.co.uk/core/website/a...
3,Australia,18,19,16,53,https://static.files.bbci.co.uk/core/website/a...
4,France,16,26,22,64,https://static.files.bbci.co.uk/core/website/a...
...,...,...,...,...,...,...
85,Peru,0,0,1,1,https://static.files.bbci.co.uk/core/website/a...
86,Qatar,0,0,1,1,https://static.files.bbci.co.uk/core/website/a...
87,Singapore,0,0,1,1,https://static.files.bbci.co.uk/core/website/a...
88,Slovakia,0,0,1,1,https://static.files.bbci.co.uk/core/website/a...
89,Zambia,0,0,1,1,https://static.files.bbci.co.uk/core/website/a...

In [30]:
list_countries  = df['countries'].to_list()
gold_medal = df['gold_medal'].to_list()
silver_medal = df['silver_medal'].to_list()
bronze_medal = df['bronze_medal'].to_list()
medal_type = ["Gold", 'Silver', 'Bronze']
url_flag = df['url_flag'].to_list()

In [31]:
country_list = []
medals = []
type_of_medal = []
flag = []

In [32]:
for i in range(len(list_countries)):

    for j in range(3):
        country_list.append(list_countries[i])
        type_of_medal.append(medal_type[j])
        flag.append(url_flag[i])

    medals.append(gold_medal[i])
    medals.append(silver_medal[i])
    medals.append(bronze_medal[i])

In [33]:
print(len(country_list), len(medals), len(type_of_medal), len(flag))

270 270 270 270

In [34]:
df_1 = pd.DataFrame({
        'countries' : country_list,
        'medal' : medals,
        'medal type':type_of_medal,
        'url_flag' : flag
})

In [35]:
df_1

,countries,medal,medal type,url_flag
0,United States,40,Gold,https://static.files.bbci.co.uk/core/website/a...
1,United States,44,Silver,https://static.files.bbci.co.uk/core/website/a...
2,United States,42,Bronze,https://static.files.bbci.co.uk/core/website/a...
3,China,40,Gold,https://static.files.bbci.co.uk/core/website/a...
4,China,27,Silver,https://static.files.bbci.co.uk/core/website/a...
...,...,...,...,...
265,Slovakia,0,Silver,https://static.files.bbci.co.uk/core/website/a...
266,Slovakia,1,Bronze,https://static.files.bbci.co.uk/core/website/a...
267,Zambia,0,Gold,https://static.files.bbci.co.uk/core/website/a...
268,Zambia,0,Silver,https://static.files.bbci.co.uk/core/website/a...
269,Zambia,1,Bronze,https://static.files.bbci.co.uk/core/website/a...

In [36]:
df_1.to_csv("data_for_bar_chart.csv")